version: "2.4"

################################################################################

services:
  darknet_ros:
    build: ./
    image: darknet_ros
    container_name: darknet_ros
    runtime: nvidia
    tty: true
    shm_size: 1G
    environment:
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1

    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./catkin_ws:/root/catkin_ws

    devices:
        - /dev/video0:/dev/video0
        - /dev/video1:/dev/video1
        - /dev/video2:/dev/video2

    network_mode: host
